### ISSUE TITLE
error when executing make l4t-32.3.1-jax

### ISSUE THREAD

**Issue by eliabruni** [idavis/jetson-containers#35]
Hi @idavis ,

Here is a first error I encountered.

When running:

```
jetson-containers$ sudo make l4t-32.3.1-jax
```

I get
```
Step 11/32 : RUN apt-get update && apt-get install -y --no-install-recommends     bzip2     lbzip2     ca-certificates     gnupg     sudo
 ---> Running in b3bd7493802f
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by idavis** [comment]
@eliabruni 

- What is your host OS?
- What container runtime are you using?
- Can you show the whole build log?

Thank you,

Ian

**Comment by eliabruni** [comment]
Hi @idavis ,

- OS: Ubuntu 18.04.4 LTS 
- runtime: Docker version 19.03.5
- Whole build log follows below

PS
`make l4t-32.2.1-jax` gives me the same error; I tried to run it on jetson-containers before #27, and it worked fine.


```
jetson-containers$ sudo make l4t-32.3.1-jax
make -C jetson-containers/docker/l4t 32.3.1-jax
make[1]: Entering directory 'jetson-containers/docker/l4t'
docker build --squash \
				--build-arg VERSION_ID="bionic-20200112" \
				--build-arg DEPENDENCIES_IMAGE=l4t:32.3.1-jax-jetpack-4.3-deps \
				-t l4t:32.3.1-jax \
				- < jetson-containers/docker/l4t/32.3.1/jax/Dockerfile
Sending build context to Docker daemon   5.12kB
Step 1/32 : ARG VERSION_ID
Step 2/32 : ARG DEPENDENCIES_IMAGE
Step 3/32 : ARG IMAGE_NAME
Step 4/32 : FROM ${DEPENDENCIES_IMAGE} as dependencies
 ---> b8f3fbbbeda1
Step 5/32 : ARG VERSION_ID
 ---> Using cache
 ---> c5b8edeaa708
Step 6/32 : FROM ubuntu:${VERSION_ID} as qemu
 ---> ccc6e87d482b
Step 7/32 : RUN apt-get update && apt-get install -y --no-install-recommends qemu-user-static &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> fd0919abbd41
Step 8/32 : ARG VERSION_ID
 ---> Using cache
 ---> 2cf05037f784
Step 9/32 : FROM arm64v8/ubuntu:${VERSION_ID}
 ---> db472617b3d1
Step 10/32 : LABEL maintainer "Ian Davis"
 ---> Using cache
 ---> 04a7b59627cc
Step 11/32 : RUN apt-get update && apt-get install -y --no-install-recommends     bzip2     lbzip2     ca-certificates     gnupg     sudo
 ---> Running in 28421b1c10e9
standard_init_linux.go:211: exec user process caused "no such file or directory"
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     bzip2     lbzip2     ca-certificates     gnupg     sudo' returned a non-zero code: 1
Makefile:29: recipe for target '32.3.1-jax' failed
make[1]: *** [32.3.1-jax] Error 1
make[1]: Leaving directory 'jetson-containers/docker/l4t'
Makefile:50: recipe for target 'l4t-32.3.1-jax' failed
make: *** [l4t-32.3.1-jax] Error 2
```

**Comment by idavis** [comment]
Hi @eliabruni , I know what the issue is. In pre #27 I copied the qemu binary into the container. Now I copy it, but for a different reason and into a different path as 4.3 requires it to be there for some of their scripting. There are two options:

1. Follow the [Configuration](https://codepyre.com/2019/12/arming-yourself/#configuration) section of [ARMing yourself](https://codepyre.com/2019/12/arming-yourself) and it should just work.
2. Add this line into your dockerfile right after `LABEL ...`
    ```docker
    # pre-req qemu binary for aarch64 emulation if this container image is built directly on x86 host
    COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin/qemu-aarch64-static
    ```
The long term option is to either put it back in the generated dockerfiles or to require people to use the 
[ARMing yourself](https://codepyre.com/2019/12/arming-yourself) post as config. I don't like either option.

**Comment by idavis** [comment]
@eliabruni This should be fixed on master now.

**Comment by eliabruni** [comment]
@idavis 

Thanks, that part passes now. I still get an error:

```
Pre-installing bootloader package, skip flashing
Setting up nvidia-l4t-multimedia-utils (32.3.1-20191209230245) ...
Setting up nvidia-l4t-3d-core (32.3.1-20191209230245) ...
Setting up libpangocairo-1.0-0:arm64 (1.40.14-1ubuntu0.1) ...
Setting up nvidia-l4t-cuda (32.3.1-20191209230245) ...
Setting up nvidia-l4t-multimedia (32.3.1-20191209230245) ...
Setting up nvidia-l4t-camera (32.3.1-20191209230245) ...
Setting up nvidia-l4t-graphics-demos (32.3.1-20191209230245) ...
Setting up nvidia-l4t-gstreamer (32.3.1-20191209230245) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for nvidia-l4t-kernel (4.9.140-tegra-32.3.1-20191209230245) ...
/
Removing QEMU binary from rootfs
Removing stashed Debian packages from rootfs
/Linux_for_Tegra/nv_tegra/nv-apply-debs.sh: line 216: /bin/rm: No such file or directory
The command '/bin/sh -c ./Linux_for_Tegra/apply_binaries.sh -r /' returned a non-zero code: 127
Makefile:29: recipe for target '32.3.1-jax' failed
make[1]: *** [32.3.1-jax] Error 127
make[1]: Leaving directory 'jetson-containers/docker/l4t'
Makefile:50: recipe for target 'l4t-32.3.1-jax' failed
make: *** [l4t-32.3.1-jax] Error 2
```

**Comment by idavis** [comment]
@eliabruni You have the best errors. The issue is that since you haven't installed the binftm service configuration. The nvidia scripts are deleting the qemu-aarch64-static file that you need to keep running. So the first `rm` succeeds, but then `rm` afterwards cannot be run.

```bash
echo "Removing QEMU binary from rootfs"
rm -f "${L4T_ROOTFS_DIR}/usr/bin/qemu-aarch64-static"

echo "Removing stashed Debian packages from rootfs"
rm -rf "${L4T_ROOTFS_DEB_DIR}"
```

**Comment by eliabruni** [comment]
Ups:) Thanks, I guess I'll install the service and run it again.

**Comment by idavis** [comment]
I'm sorry you've hit these issues. I have a fix, just trying to get it built out.

**Comment by eliabruni** [comment]
No worries, I'm happy I can provide some little feedback!

**Comment by idavis** [comment]
@eliabruni  This should now be fixed. Thank you again.

**Comment by eliabruni** [comment]
It is, thanks!
